### ISSUE TITLE
Architecture this was created for?

### ISSUE THREAD

**Issue by adwaraki** [jmrf/pyBPE#1]
I am trying to get this to run on macOS and have run into a lot of issues. What architecture was this created on (guessing Linux?).

I first had issues where the cmake command would not run because of it using clang. I had to get around that by doing
```
# IF(CMAKE_COMPILER_IS_GNUCXX)
ADD_DEFINITIONS("-Wall")
# ELSE()
#  MESSAGE(FATAL_ERROR "CMakeLists.txt has not been tested/written for your compiler.")
#ENDIF()
```

and using the command `cmake -DCMAKE_C_COMPILER=/usr/bin/gcc -DCMAKE_CXX_COMPILER=/usr/bin/g++ ..`.

This wrote all the MakeFiles, but then using `make` throws the following errors:

```
9 warnings generated.
[100%] Linking CXX shared library libpybpe.dylib
Undefined symbols for architecture x86_64:
  "_PyDict_Type", referenced from:
      boost::python::converter::pyobject_type<boost::python::dict, &(PyDict_Type)>::get_pytype() in fast.cpp.o
  "_PyList_Type", referenced from:
      boost::python::converter::pyobject_type<boost::python::list, &(PyList_Type)>::get_pytype() in fast.cpp.o
  "_PyLong_FromUnsignedLong", referenced from:
      boost::python::converter::arg_to_python<unsigned int>::arg_to_python(unsigned int const&) in fast.cpp.o
  "_PyTuple_New", referenced from:
      boost::python::tuple boost::python::make_tuple<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, unsigned int>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, unsigned int const&) in fast.cpp.o
  "_PyUnicode_FromStringAndSize", referenced from:
      boost::python::converter::arg_to_python<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > >::arg_to_python(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in fast.cpp.o
      boost::python::to_python_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in fast.cpp.o
  "_PyUnicode_Type", referenced from:
      boost::python::to_python_value<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&>::get_pytype() const in fast.cpp.o
  "__Py_NoneStruct", referenced from:
      boost::python::api::object::object() in fast.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libpybpe.dylib] Error 1
make[1]: *** [CMakeFiles/pybpe.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by adwaraki** [comment]
Solved this by modifying the CMakeLists.txt as follows:

```
CMAKE_MINIMUM_REQUIRED(VERSION 2.8)

find_package(PythonInterp 3)
find_package(PythonLibs 3)

IF(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE "DEBUG")
  #set(CMAKE_BUILD_TYPE "RELEASE")
  #set(CMAKE_BUILD_TYPE "RELWITHDEBINFO")
  #set(CMAKE_BUILD_TYPE "MINSIZEREL")
ENDIF()

SET (BOOST_ROOT "/usr/local/opt/boost/")
SET (BOOST_INCLUDEDIR "/usr/local/opt/boost/include")
SET (BOOST_LIBRARYDIR "/usr/local/opt/boost/lib")

find_package(Boost)

message(STATUS "Boost_FOUND: ${Boost_FOUND}")
message(STATUS "Boost_INCLUDE_DIRS: ${Boost_INCLUDE_DIRS}")
message(STATUS "Boost_LIBRARY_DIRS: ${Boost_LIBRARY_DIRS}")
message(STATUS "Boost_LIBRARIES: ${Boost_LIBRARIES}")
message(STATUS "PYTHON_INCLUDE: $ENV{PYTHON_INCLUDE}")

find_package(PythonLibs REQUIRED)

message("Python_INCLUDE_DIRS: " ${PYTHON_INCLUDE_DIRS} )
message("Python_LIBRARY_DIRS: " ${PYTHON_LIBRARIES} )

IF(Boost_FOUND)
  set(CMAKE_CXX_STANDARD 11)
  set(Boost_USE_STATIC_LIBS OFF)
  set(Boost_USE_MULTITHREADED ON)
  set(Boost_USE_STATIC_RUNTIME OFF)
  find_package(Boost 1.68.0 COMPONENTS python3.7)

  include_directories(${Boost_INCLUDE_DIRS} ${PYTHON_INCLUDE_DIRS})
  link_directories(${Boost_LIBRARY_DIRS})
  include_directories("${Boost_INCLUDE_DIRS}" $ENV{PYTHON_INCLUDE} })
  ADD_DEFINITIONS( "-DHAS_BOOST" )
  add_library(pybpe SHARED fast.cpp)
  target_link_libraries(pybpe ${Boost_LIBRARIES} ${PYTHON_LIBRARIES})
ELSEIF(NOT Boost_FOUND)
  MESSAGE(FATAL_ERROR "Unable to find correct Boost version. Did you set BOOST_ROOT?")
ENDIF()

# IF(CMAKE_COMPILER_IS_GNUCXX)
ADD_DEFINITIONS("-Wall")
  # ELSE()
  #  MESSAGE(FATAL_ERROR "CMakeLists.txt has not been tested/written for your compiler.")
  #ENDIF()
```

This is for Python 3.7 running on macOS Mojave, with boost and boost-python3 installed using HomeBrew to brew's default locations. 

You need to invoke cmake to use gcc and g++ instead of clang with the command listed in the issue above. After that, make works successfully. Hope this is useful for someone working on macOS and you hopefully don't end up spending an entire day figuring out how to get this to work nice without Conda, and with gcc.

**Comment by adwaraki** [comment]
Encountering an error running the conftest.py within a virtual environment with everything setup properly.

```
Traceback (most recent call last):
  File "conftest.py", line 4, in <module>
    from pybpe import pyBPE
  File "/Users/Abhishek/Projects/Git-Repositories/pyBPE/pybpe/pybpe.py", line 11, in <module>
    import libpybpe as bpe
ImportError: dlopen(/Users/Abhishek/Projects/Git-Repositories/pyBPE/pybpe/libpybpe.so, 2): no suitable image found.  Did find:
	/Users/Abhishek/Projects/Git-Repositories/pyBPE/pybpe/libpybpe.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
	/Users/Abhishek/Projects/Git-Repositories/pyBPE/pybpe/libpybpe.so: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x03
```

**Comment by adwaraki** [comment]
Never mind. Stupid mistake. The code builds `libpybpe.dylib` in the build folder. Just relocate that file to the `pybpe` folder and it should work. Overlooked it since I expected the cmake scripts to be writing it to `libpybpe.so`, ignoring the fact that I was on macOS. 🤦🏻‍♂️
